const blogData = [
    {
        "id": "69958236360142f457e82168",
        "title": "Wilujeng Saum Ramadhan 1447 H",
        "description": "Keluarga Besar Kasepuhan Gelaralam Seja Ngawilujengkeun Saum Ramadhan 1447 H",
        "content": "\u003cp\u003eWilujeng Saum Ramadhan 1447 H\u003c/p\u003e",
        "day": 18,
        "month": "Februari",
        "year": 2026,
        "image": "https://raw.githubusercontent.com/gelaralam/img/main/2026/02/d59bc54a-f27c-46a9-a3b6-ae974eca6ed4.jpeg",
        "video_url": "",
        "category": "BERITA"
    },
    {
        "id": "698c4234360142f457e82166",
        "title": "NGAREREMOKEUN",
        "description": "Ngareremokeun berarti Meramaikan, dalam pandangan masyarakat kasepuhan, padi dibagi menjadi dua entitas, yaitu Pare Awewe dan Pare Lalaki yang nantinya hasil dari perkawinan tersbut melahirkan entitas bernama Pare Indung.",
        "content": "\u003cp\u003eNgareremokeun berarti Meramaikan, dalam pandangan masyarakat kasepuhan, padi dibagi menjadi dua entitas, yaitu Pare Awewe dan Pare Lalaki yang nantinya hasil dari perkawinan tersbut melahirkan entitas bernama Pare Indung. Simbol Pare Indung bermakna asal dan kesatuan dimana sudah tidak ada lagi konsepsi peran Laki-laki dan Perempuan dan hanya menghasilkan entitas Tunggal bernama Indung. Karena maknanya yang sangat dalam dan perannya sangat dihormati, pare indung wajib dibageakeun (dibahagiakan) dalam siklus tiga tahun setelah perpindahan dilanjut setiap delapan tahun sekali dalam Ritual Ngareremokeun. Setiap kaolotan dari 568 diwajibkan membawa satu pocong pare indung pada ritual tersebut, dan seluruh orang yang terlibat dalam ritual diwajibkan untuk memakai baju putih dan iket putih sebagai penanda kemurnian acara dan kesakralan acara.\u003c/p\u003e\n\u003cp\u003eAngklung dogdog lojor merupakan salah satu seni yang disakralkan oleh masyarakat kasepuhan karena perannya yang sentral pada setiap perayaan-perayaan inti kasepuhan termasuk pada ritual Ngareremokeun. Tradisi ngareremokeun merupakan tradisi langka yang hanya dilaksanakan ketika kasepuhan baru menginjaki tiga tahun pertama setelah perpindahan, untuk kemudian tradisi ngareremokeun ini diadakan pada delapan tahun selanjutnya mengikuti itungan Sawindu.\u003c/p\u003e",
        "day": 11,
        "month": "Pebruari",
        "year": 2026,
        "image": "https://raw.githubusercontent.com/gelaralam/img/main/2026/02/92a871d7-657b-4fcb-9cf9-7e6b8fa601a8.PNG",
        "video_url": "https://www.youtube.com/watch?v=JO0EzJLuePg",
        "category": "TRADISI"
    },
    {
        "id": "698466877fdb784eef848783",
        "title": "Pesan dari Abah Ugi",
        "description": "Terjadi banyak penipuan mengatas namakan Abah Ugi...",
        "content": "\u003cp\u003eAbah Ugi berpesan agar berhati-hati kepada seluruh masyarakat, dimana akhir-akhir banyak terjadi penipuan mengatasnamakan Abah Ugi. Untuk itu Abah Ugi berpesan agar bisa lebih bijak dalam menggunakan media seluler ataupun media sosial lainnya. Jika membutuhkan informasi segera menghubungi no telpon yang tercantum di website resmi Kasepuhan Gelaralam https://gelaralam.id/ atau kirim email di info@gelaralam.id\u003c/p\u003e",
        "day": 5,
        "month": "Pebruari",
        "year": 2026,
        "image": "https://raw.githubusercontent.com/gelaralam/img/main/2026/02/db2ba0e0-a39d-4185-a278-10698489ceae.jpg",
        "video_url": "https://youtube.com/shorts/RKwOolEDl9g?feature=share",
        "category": "BERITA"
    },
    {
        "id": "697f4b8bb1ce76ed2c68f55c",
        "title": "Rajaban di Kasepuhan Gelaralam",
        "description": "Sabtu, 31 Januari 2026 menjadi malam yang berbeda di antara malam-malam 31 Januari di tahun sebelumnya…",
        "content": "\u003cp\u003eRAJABAN DI KASEPUHAN GELARALAM\u003c/p\u003e\n\u003cp\u003eSabtu, 31 Januari 2026 menjadi malam yang berbeda di antara malam-malam 31 Januari di tahun sebelumnya, Kasepuhan Gelaralam mengadakan Pengajian dan Khutbah bersama dalam suasana bulan Rajab dan kentalnya perjalanan Isra Miraj.\u003c/p\u003e\n\u003cp\u003eAcara tersebut diinisiasi oleh para DKM masjid Kasepuhan Gelaralam dan diikuti oleh ratusan Incu-Putu yang tersebar di Dusun Sukamulya, Desa Sirnaresmi dan dihadiri oleh Kepada Desa Sirnaresmi, Bapak Jaro Iwan Suwandi.\u003c/p\u003e\n\u003cp\u003eDalam pengetahuan traditional Kasepuhan Gelaralam, dikenal istilah Sara, Nagara, Mokaha yang dalam artian singkat Bariskolot berarti tiga pilar keutamaan hidup mencakup: Sara sebagai pondasi awal kehidupan yang dilandasi dari pola Agama, Nagara sebagai pondasi kebangsaan agar setiap orang dapat menanamkan Nasionalism dalam berkehidupan, dan Mokaha yang berarti Adat atau Tradisi yang menjadi tumpuan agar setiap masyarakat tidak kehilangan jati diri sebagai orang yang berbudaya.\u003c/p\u003e\n\u003cp\u003eMenurut Jaro Iwan selaku pemangku kebijakan desa, ia sangat menyambut acara rajaban tersebut karena menjadi sebuah pengingat bahwa masyarakat kasepuhan masih mengenal Sara yang dibungkus dalam balut tradisi, sehingga  ada keselarasan antara unsur agama beserta budaya yang masih terlihat di kawasan Kasepuhan Gelaralam. Ia berharap semoga tahun depan acara tersebut lebih tertara dan lebih baik, serta mengingatkan pentingnya agama sebagai landasan agar kita tetap menjadi masyarakat adat yang tidak anti terhadap nilai-nilai agama.\u003c/p\u003e\n\u003cp\u003e(Tama)\u003c/p\u003e",
        "day": 1,
        "month": "Pebruari",
        "year": 2026,
        "image": "https://raw.githubusercontent.com/gelaralam/img/main/2026/02/e090f04e-55cf-4864-bcaf-72a7a31e329d.jpeg",
        "video_url": "https://youtube.com/shorts/AtKTXjnxIzM",
        "category": "TRADISI"
    },
    {
        "id": "6979e91bb132082d0bf304a8",
        "title": "Ngahiras Kampung Adat Ciptarasa",
        "description": "Kegiatan pertanian Ngahiras di Kampung Adat Ciptarasa",
        "content": "\u003cp\u003eKegiatan pertanian Ngahiras di Kampung Adat Ciptarasa (A Dewan)\u003c/p\u003e",
        "day": 28,
        "month": "Januari",
        "year": 2026,
        "image": "https://raw.githubusercontent.com/gelaralam/img/main/2026/01/2581abcd-e161-4e73-be9f-d0bae7cb2758.PNG",
        "video_url": "https://youtube.com/shorts/HDrBT2Paf0U?si=ERxZmZQqIbFJ9eLJ",
        "category": "PERTANIAN"
    },
    {
        "id": "69785d71f3ee1c83cf4744cd",
        "title": "Selamat Datang di Website resmi Kasepuhan Gelaralam",
        "description": "Telah hadir website resmi Kasepuhan Gelaralam. Semoga bisa menjadi sarana informasi untuk semuanya.",
        "content": "\u003cp\u003eKami dengan bangga mengumumkan peluncuran website resmi Kasepuhan Gelaralam. Platform digital ini dibangun untuk menjadi pusat informasi mengenai sejarah, tradisi, agenda kegiatan, dan berita terbaru seputar kehidupan masyarakat adat di Gelaralam.\u003c/p\u003e\u003cp\u003eSeiring dengan perkembangan zaman, kehadiran website ini diharapkan dapat memudahkan masyarakat luas, baik peneliti, wisatawan, maupun generasi muda Sunda, untuk mempelajari kearifan lokal yang kami jaga selama ratusan tahun.\u003c/p\u003e\u003cp\u003eDi website ini, pengunjung dapat menemukan:\u003c/p\u003e\u003cul\u003e\u003cli\u003eSejarah berdirinya Kasepuhan Gelaralam dari tahun 1368.\u003c/li\u003e\u003cli\u003eJadwal upacara adat tahunan seperti Serentaun.\u003c/li\u003e\u003cli\u003eGaleri foto dan video tradisi pertanian padi.\u003c/li\u003e\u003cli\u003eBlog berita dan kegiatan terbaru.\u003c/li\u003e\u003c/ul\u003e\u003cp\u003eSemoga website ini bermanfaat bagi kita semua dalam upaya melestarikan budaya dan menjaga harmoni dengan alam.\u003c/p\u003e",
        "day": 23,
        "month": "Januari",
        "year": 2026,
        "image": "assets/blog/blog-2.jpg",
        "video_url": "",
        "category": "PENGUMUMAN"
    },
    {
        "id": "69785d71f3ee1c83cf4744cc",
        "title": "Bantuan Modal Usaha dari Baznas Jabar",
        "description": "@baznasjabar memberikan bantuan modal usaha yang diberikan kepada Kasepuhan Gelaralam berupa Modal usaha Kopi Ciptagelar. \"Zakat yang ditunaikan bukan hanya menjadi bantuan ekonomi, tetapi juga penguat semangat, penjaga kearifan, dan jalan menuju usaha mandiri.\" kutipan dari media sosial instagram baznasjabar. Terima kasih.",
        "content": "\u003cp\u003eBAZNAS Provinsi Jawa Barat secara resmi menyalurkan bantuan modal usaha untuk pengembangan Kopi Ciptagelar di Kasepuhan Gelaralam. Bantuan ini merupakan bagian dari program pemberdayaan ekonomi masyarakat adat untuk meningkatkan kesejahteraan lahir dan batin.\u003c/p\u003e\u003cp\u003e\"Zakat yang ditunaikan bukan hanya menjadi bantuan ekonomi, tetapi juga penguat semangat, penjaga kearifan, dan jalan menuju usaha mandiri,\" tulis akun resmi @baznasjabar.\u003c/p\u003e\u003cp\u003eKopi Ciptagelar sendiri merupakan produk unggulan kasepuhan yang ditanam dengan cara tradisional dan memiliki cita rasa khas pegunungan Sukabumi. Dengan adanya modal usaha ini, diharapkan proses produksi dan pemasaran bisa lebih luas lagi.\u003c/p\u003e\u003cp\u003eAbah Ugi Sugriana Rakasiwi selaku Ketua Adat Kasepuhan Gelaralam menyampaikan apresiasi yang mendalam atas perhatian dari pihak BAZNAS. \"Ini bukan sekadar bantuan uang, tapi bentuk kepercayaan kepada kami untuk tetap mandiri di atas tanah leluhur,\" ujarnya.\u003c/p\u003e",
        "day": 15,
        "month": "Januari",
        "year": 2026,
        "image": "assets/blog/blog-1.jpg",
        "video_url": "",
        "category": "EKONOMI"
    },
    {
        "id": "69785d71f3ee1c83cf4744ce",
        "title": "Warga Kasepuhan Gelaralam siap dengan produk barunya",
        "description": "Kang Ade Pian Supriandi atau warga adat lebih mengenal beliau dengan sebutan A Dewan, sedang bersiap meluncurkan produk terbarunya dan bisa menjadi kebanggaan bagi warga adat di Kasepuhan Gelaralam, tunggu tanggal mainnya!.",
        "content": "\u003cp\u003eKabar gembira datang dari sektor ekonomi kreatif Kasepuhan Gelaralam. Kang Ade Pian Supriandi (A Dewan) tengah mempersiapkan peluncuran produk terbaru asli buatan warga adat.\u003c/p\u003e\u003cp\u003eMeskipun masih bersifat rahasia terkait detail produknya, A Dewan memberikan bocoran bahwa produk ini tetap akan membawa ruh kearifan lokal Kasepuhan Gelaralam namun dengan sentuhan yang lebih modern dan dapat diterima oleh pasar yang lebih luas.\u003c/p\u003e\u003cp\u003e\"Kita ingin membuktikan bahwa masyarakat adat juga mampu berinovasi tanpa harus meninggalkan akar budayanya. Tunggu saja kejutannya dalam waktu dekat,\" ungkap A Dewan saat ditemui di bengkel produksinya.\u003c/p\u003e\u003cp\u003ePeluncuran produk ini juga menjadi bagian dari upaya pemberdayaan ekonomi kreatif bagi para pemuda di lingkungan kasepuhan.\u003c/p\u003e",
        "day": 21,
        "month": "Desember",
        "year": 2025,
        "image": "assets/blog/blog-3.jpg",
        "video_url": "",
        "category": "KREATIVITAS"
    },
    {
        "id": "69785d71f3ee1c83cf4744d1",
        "title": "PANTUN SUNDA",
        "description": "Berbeda dengan Seni Pantun Melayu, Seni Pantun Sunda berisi mengenai cerita kesejarahan yang dilagamkan dalam bentuk tutur kata dengan iringan Kecapi dan penyediaan Sajen pada sekelilingnya...",
        "content": "\u003cp\u003eBerbeda dengan Seni Pantun Melayu, Seni Pantun Sunda berisi mengenai cerita kesejarahan yang dilagamkan dalam bentuk tutur kata dengan iringan Kecapi dan penyediaan Sajen pada sekelilingnya. Seni Pantun Sunda telah tercatat dalam Naskah Kuna Sanghiyang Siksa Kandang Karesian (Kropak 630).\u003c/p\u003e\u003cp\u003ePada Saat ini Pantun Sunda sudah jarang dipentaskan. “Proses menjadi seorang Juru Pantun tidak semudah yang dibayangkan. tidak ada audisi atau sekolah karena proses untuk menjadi Juru Pantun adalah ketika seseorang menerima Wangsit atau Pituduh dari Karuhun.” Tutur Ki Arsan (50 tahun) yang merupakan Juru Pantun dari Kasepuhan Ciptagelar, Banten Kidul.\u003c/p\u003e\u003cp\u003eMenurut Penuturan Ki Arsan, seorang Juru Pantun adalah orang yang dipilih oleh Karuhun untuk bercerita dalam Acara-acara Khusus seperti Ritual Adat Ngaseuk, Ritual Adat Mipit, dan Ruwatan. (TAMA)\u003c/p\u003e",
        "day": 5,
        "month": "Agustus",
        "year": 2025,
        "image": "assets/blog/kiarsan.jpg",
        "video_url": "",
        "category": "STORY"
    },
    {
        "id": "69785d71f3ee1c83cf4744d0",
        "title": "ANGKLUNG DAN PADI",
        "description": "Angklung adalah salahsatu Kesenian dari Tatar Sunda dimana bahan utama Angklung adalah Bambu yang dirangkai sedemikian rupa dan pola membentuk tangga nada Da, Mi, Na, Ti, La, Da.",
        "content": "\u003cp\u003eAngklung adalah salahsatu Kesenian dari Tatar Sunda dimana bahan utama Angklung adalah Bambu yang dirangkai sedemikian rupa dan pola membentuk tangga nada Da, Mi, Na, Ti, La, Da. Pada saat ini kita Mengenal Angklung lewat peran Kang Udjo, seorang Maestro seni Sunda yang berhasil membawa Angklung dikenal oleh Khalayak umum, bahkan disahkan oleh UNESCO sebagai warisan budaya dunia dari Indonesia. Namun, tak banyak orang tahu bahwa di Banten Kidul Angklung merupakan Kesenian Sakral yang erat hubungannya dengan sosok Dewi Sri atau yang kita kenal sebagai Padi dalam Mitologi Sunda Kuna. Pelaku Angklung Dogdog Lojor mengatakan bahwa dirinya sudah menggeluti Kesenian ini hampir 40 tahun.\u003c/p\u003e\u003cp\u003eAki Dai menjelaskan bahwa ketika pemimpin Adat akan melaksanakan Ngaseuk/ menanam padi, maka tugas Aki Dai adalah menghaturkan Kidung permohonan maaf kepada semua Makhluk ciptaanNya dan juga Kidung permintaan agar acara Ngaseuk dapat berjalan dengan lancar. Aki Dai mempercayai bahwa Getaran yang dihasilkan oleh Angklung dan Dogdog ini dapat membahagiakan Padi, “Seperti manusia yang senang dan bahagia ketika mendengar musik, padi pun sama,” ujar Aki Dai. (TAMA)\u003c/p\u003e",
        "day": 28,
        "month": "Juli",
        "year": 2025,
        "image": "assets/blog/angklung.jpg",
        "video_url": "",
        "category": "STORY"
    },
    {
        "id": "69785d71f3ee1c83cf4744cf",
        "title": "Di Kampung Ini Padi Adalah Nadi",
        "description": "Nendra (10 tahun) tampak semangat ketika membantu kakeknya yang sedang mengunjal Padi dari sawah milik kakeknya menuju Leuit atau Lumbung Padi khas Kasepuhan Gelaralam.",
        "content": "\u003cp\u003eNendra (10 tahun) tampak semangat ketika membantu kakeknya yang sedang mengunjal Padi dari sawah milik kakeknya menuju Leuit atau Lumbung Padi khas Kasepuhan Gelaralam.Begitu juga dengan teman sebayanya yang sudah terbiasa memikul pocongan Padi untuk dibawa ke Leuit, sebelum akhirnya dirapihkan di dalam Leuit.\u003c/p\u003e\u003cp\u003eBerbeda dengan anak seusianya di Kota yang telah terkontaminasi gadged atau game online lainnya, Nendra dan kawan-kawannya lebih senang bermain dengan pikulan padi. Menurut penuturan Aki Koyod (47 tahun) yang menjabat sebagai Rorokan Pare Kasepuhan Gelaralam, anak kecil di sini sudah diajarkan untuk mengenal padi sebelum pada akhirnya mereka Sakuren atau Menikah. “Memperkenalkan padi kepada anak-anak kecil di sini sudah menjadi kewajiban Masyarakat Adat Gelaralam, karena dalam pandangan Aki, Padi adalah salahsatu bahan yang harus dikenali sejak dini,” ungkap Aki Koyod.\u003c/p\u003e\u003cp\u003ePadi bukan hanya sebagai bahan pokok semata, dalam pandangan Tradisi Masyarakat Gelaralam, padi merupakan Makhluk yang sama seperti manusia. Tak ayal proses penanaman padi di Kasepuhan Gelaralam seperti hal nya kita mengurusi Manusia dari mulai kecil, dewasa hingga akhirnya menikah dan beranak. “Rurukan berarti merawat, berasal dari kata Ruruk yang artinya memomong,” Aki Koyod.\u003c/p\u003e\u003cp\u003eTradisi menanam Padi satu tahun sekali masih mereka pertahankan hingga saat ini, terhitung 160 variates padi masih mereka pertahankan sejak 1368 hingga saat ini. Dalam proses padi menjadi beras, mereka masih menggunakan Tradisi lama, dari mulai Ngaseuk atau menanam padi Huma Ladang yang memakai metode tongkat untuk melubangi tanah, hingga memakai Ani-ani sebagai alat untuk memotong padi dari tangkai nya ketika masa panen telah tiba. Tradisi ini merupakan warisan yang wajib dijaga oleh Masyarakat Gelaralam, karena sesuai dengan amanat Leluhur mereka jika “Kudu bisa ngigelan jeung ngigelkeun jaman, tapi ulah kababawa ku jaman,” yang berarti Kita harus bisa beradaptasi akan perkembangan jaman, tapi jangan sesekali tergerus oleh jaman.\u003c/p\u003e\u003cp\u003eTidak seperti di Kanekes Baduy dimana anak kecil disana tidak diwajibkan untuk sekolah, Masyarakat Gelaralam membuka dirinya dengan hal berbau Teknologi, digital, dan Pendidikan. Mereka biasa bersekolah hingga Sekolah Menengah Atas untuk selanjutnya mereka dapat meilih antara bekerja di Kota atau kembali menjadi seorang Petani dan penggarap Kebun. Dapat disimpulkan jika Masyarakat Kasepuhan dapat hidup dalam keseimbangan menjaga Tradisi dan juga tidak menutup akan perkambangan jaman yang bersifat masivve. (TAMA)\u003c/p\u003e",
        "day": 23,
        "month": "Juli",
        "year": 2025,
        "image": "assets/blog/kampung-padi.jpg",
        "video_url": "",
        "category": "STORY"
    }
];